app:
  env: "local"
  log_level: "debug"

telegram:
  token: "8525306004:AAGDl3c1OGW7JIwX7zTZ7nF9eR49YcASonY"

http:
  host: "0.0.0.0"
  port: 8080

database:
  sqlite_path: "./data/app.db"

dragonfly:
  addr: "localhost:6379"
  password: ""
  db: 0
